export enum UserConstants {
    ADD_USER_CONTACTS_DATA = 'ADD_USER_CONTACTS_DATA',
    ADD_USER_INFORMATION_DATA = 'ADD_USER_INFORMATION_DATA',
    ADD_USER_CATEGORIES_DATA = 'ADD_USER_CATEGORIES_DATA',
    REQUEST_USER_DATA = 'REQUEST_USER_DATA',
    REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS',
    REQUEST_USER_ERROR = 'REQUEST_USER_ERROR',
    SET_STEP = 'SET_STEP',
    CLEAR_USER = 'CLEAR_USER',
}